<a href="https://colab.research.google.com/github/salmashaik779907-stack/Data-analysis-/blob/main/Case_Study_E_commerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛒 E-Commerce Sales Performance

**Company:** SwiftCart Retail
**Role:** Sales Operations Analyst

## 🏢 Scenario

SwiftCart Retail is looking to optimize its inventory for the next quarter. You have been assigned to identify which product categories are **“cash cows”** and which ones are underperforming based on sales performance and customer feedback.

---

## 🎯 Your Tasks

### 1️⃣ Calculate Revenue

* Create a new column called **`Total_Sales`** using the formula:

```
Total_Sales = Price × Quantity
```

* This will represent the total revenue generated per product.

---

### 2️⃣ Identify Top Performers

* Group the data by **Category**.
* Calculate total sales per category.
* Determine which category has the **highest total sales**.

---

### 3️⃣ Customer Satisfaction Analysis

* Compute the **average product rating** across all products.
* Briefly interpret what this means for overall customer satisfaction.

---

### 4️⃣ Premium Product Filtering

* Filter and list all products where:

```
Rating > 4
```

* These represent high-performing, highly rated products.

---

### 5️⃣ Visualization – Sales Performance

* Create a **Bar Chart** showing:

```
Category vs. Total Sales
```

* Include:

  * Chart title
  * Axis labels
  * Clear formatting for readability

---

### 6️⃣ Pricing Analysis

* Create a **Histogram** of product prices.
* Analyze:

  * Most common price ranges
  * Price distribution trends

---

## 📌 Expected Outcome

By completing this analysis, you should be able to:

* Identify high-revenue product categories
* Understand customer satisfaction trends
* Recognize premium-performing products
* Analyze pricing distribution
* Provide data-driven recommendations for inventory optimization

---

In [ ]:
# 1. Math operation
df['Total_Sales'] = df['Price'] * df['Quantity']

# 2. Grouping
df.groupby('Category')['Total_Sales'].sum().sort_values(ascending=False)

# 5. Bar Chart
df.groupby('Category')['Total_Sales'].sum().plot(kind='bar')

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/ecommerce_sales_dataset.csv")

In [ ]:
df

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
# Understanding columns present which are the features of the Data
df.columns

Index(['Order_ID', 'Product_Category', 'Price', 'Quantity', 'Customer_Rating'], dtype='object')

In [ ]:
# Print first 5 Rows
df.head()

   Order_ID Product_Category  Price  Quantity  Customer_Rating
0      1001            Books   1894         4              3.8
1      1002      Electronics   2210         1              4.6
2      1003         Clothing    897         2              4.2
3      1004         Clothing   3890         1              2.8
4      1005      Electronics   3529         3              3.6

In [ ]:
df.tail()

    Order_ID Product_Category  Price  Quantity  Customer_Rating
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
# Valuable Information about the Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          20 non-null     int64
 1   Product_Category  20 non-null     object
 2   Price             20 non-null     int64
 3   Quantity          20 non-null     int64
 4   Customer_Rating   20 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes

In [ ]:
# Statistics of Data
df.describe()

         Order_ID        Price   Quantity  Customer_Rating
count    20.00000    20.000000  20.000000        20.000000
mean   1010.50000  2334.050000   3.050000         3.855000
std       5.91608  1077.293073   1.538112         0.889397
min    1001.00000   331.000000   1.000000         2.500000
25%    1005.75000  1840.250000   2.000000         2.975000
50%    1010.50000  2288.500000   3.000000         4.000000
75%    1015.25000  3176.000000   4.250000         4.725000
max    1020.00000  3890.000000   5.000000         5.000000

In [ ]:
df

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
# How many are the total orders today?
len(df)

20

In [ ]:
# How many product categories the company has?
df["Quantity"]

0     4
1     1
2     2
3     1
4     3
5     2
6     3
7     4
8     4
9     5
10    5
11    1
12    2
13    2
14    2
15    4
16    5
17    5
18    1
19    5
Name: Quantity, dtype: int64

In [ ]:
# Cacluclate Average Price of today's sales
df["Price"].mean() # Customer Segmentation , Customer Spending Patterns

np.float64(2334.05)

In [ ]:
df["Price"].max()

3890

In [ ]:
df["Price"].min()

331

In [ ]:
df

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
df["Price"]

0     1894
1     2210
2      897
3     3890
4     3529
5     2228
6      697
7     2349
8     3522
9     3080
10    1981
11    1679
12    2130
13     733
14    2742
15    2703
16     331
17    3863
18    3464
19    2759
Name: Price, dtype: int64

In [ ]:
df["Price"] > 3000

0     False
1     False
2     False
3      True
4      True
5     False
6     False
7     False
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19    False
Name: Price, dtype: bool

In [ ]:
df[df["Price"] > 3000]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [ ]:
df[df["Customer_Rating"] > 3.5]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
9       1010             Home   3080         5              4.4
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
15      1016             Home   2703         4              5.0
19      1020         Clothing   2759         5              5.0

In [ ]:
df

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
df[df["Product_Category"] == "Electronics"]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
1       1002      Electronics   2210         1              4.6
4       1005      Electronics   3529         3              3.6
11      1012      Electronics   1679         1              4.8
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [ ]:
df[df["Product_Category"] == "Clothing"]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
14      1015         Clothing   2742         2              2.6
19      1020         Clothing   2759         5              5.0

In [ ]:
len(df[df["Product_Category"] == "Clothing"])

4

In [ ]:
df[df["Price"] > 3000]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [ ]:
df[(df["Product_Category"]=="Electronics") & (df["Price"] > 3000)]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
4       1005      Electronics   3529         3              3.6
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [ ]:
df[df["Product_Category"]=="Electronics"]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
1       1002      Electronics   2210         1              4.6
4       1005      Electronics   3529         3              3.6
11      1012      Electronics   1679         1              4.8
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [ ]:
(df["Price"] > 3000)

0     False
1     False
2     False
3      True
4      True
5     False
6     False
7     False
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19    False
Name: Price, dtype: bool

In [ ]:
df[(df["Product_Category"]=="Electronics") & (df["Customer_Rating"] > 3.5)]

    Order_ID Product_Category  Price  Quantity  Customer_Rating
1       1002      Electronics   2210         1              4.6
4       1005      Electronics   3529         3              3.6
11      1012      Electronics   1679         1              4.8

In [ ]:
df

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [ ]:
df.sort_values("Price")

    Order_ID Product_Category  Price  Quantity  Customer_Rating
16      1017      Electronics    331         5              3.1
6       1007             Home    697         3              4.8
13      1014             Home    733         2              2.9
2       1003         Clothing    897         2              4.2
11      1012      Electronics   1679         1              4.8
0       1001            Books   1894         4              3.8
10      1011             Home   1981         5              3.0
12      1013             Home   2130         2              4.2
1       1002      Electronics   2210         1              4.6
5       1006             Home   2228         2              4.7
7       1008             Home   2349         4              4.8
15      1016             Home   2703         4              5.0
14      1015         Clothing   2742         2              2.6
19      1020         Clothing   2759         5              5.0
9       1010             Home   3080         5              4.4
18      1019      Electronics   3464         1              3.4
8       1009             Home   3522         4              2.5
4       1005      Electronics   3529         3              3.6
17      1018      Electronics   3863         5              2.9
3       1004         Clothing   3890         1              2.8

In [ ]:
df.sort_values("Customer_Rating")

    Order_ID Product_Category  Price  Quantity  Customer_Rating
8       1009             Home   3522         4              2.5
14      1015         Clothing   2742         2              2.6
3       1004         Clothing   3890         1              2.8
13      1014             Home    733         2              2.9
17      1018      Electronics   3863         5              2.9
10      1011             Home   1981         5              3.0
16      1017      Electronics    331         5              3.1
18      1019      Electronics   3464         1              3.4
4       1005      Electronics   3529         3              3.6
0       1001            Books   1894         4              3.8
12      1013             Home   2130         2              4.2
2       1003         Clothing    897         2              4.2
9       1010             Home   3080         5              4.4
1       1002      Electronics   2210         1              4.6
5       1006             Home   2228         2              4.7
7       1008             Home   2349         4              4.8
6       1007             Home    697         3              4.8
11      1012      Electronics   1679         1              4.8
15      1016             Home   2703         4              5.0
19      1020         Clothing   2759         5              5.0

In [ ]:
df.sort_values("Price", ascending=False)

    Order_ID Product_Category  Price  Quantity  Customer_Rating
3       1004         Clothing   3890         1              2.8
17      1018      Electronics   3863         5              2.9
4       1005      Electronics   3529         3              3.6
8       1009             Home   3522         4              2.5
18      1019      Electronics   3464         1              3.4
9       1010             Home   3080         5              4.4
19      1020         Clothing   2759         5              5.0
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
7       1008             Home   2349         4              4.8
5       1006             Home   2228         2              4.7
1       1002      Electronics   2210         1              4.6
12      1013             Home   2130         2              4.2
10      1011             Home   1981         5              3.0
0       1001            Books   1894         4              3.8
11      1012      Electronics   1679         1              4.8
2       1003         Clothing    897         2              4.2
13      1014             Home    733         2              2.9
6       1007             Home    697         3              4.8
16      1017      Electronics    331         5              3.1

In [ ]:
df.sort_values("Customer_Rating", ascending=False)

    Order_ID Product_Category  Price  Quantity  Customer_Rating
15      1016             Home   2703         4              5.0
19      1020         Clothing   2759         5              5.0
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
11      1012      Electronics   1679         1              4.8
5       1006             Home   2228         2              4.7
1       1002      Electronics   2210         1              4.6
9       1010             Home   3080         5              4.4
2       1003         Clothing    897         2              4.2
12      1013             Home   2130         2              4.2
0       1001            Books   1894         4              3.8
4       1005      Electronics   3529         3              3.6
18      1019      Electronics   3464         1              3.4
16      1017      Electronics    331         5              3.1
10      1011             Home   1981         5              3.0
17      1018      Electronics   3863         5              2.9
13      1014             Home    733         2              2.9
3       1004         Clothing   3890         1              2.8
14      1015         Clothing   2742         2              2.6
8       1009             Home   3522         4              2.5

In [ ]:
df[["Quantity", "Price"]]

    Quantity  Price
0          4   1894
1          1   2210
2          2    897
3          1   3890
4          3   3529
5          2   2228
6          3    697
7          4   2349
8          4   3522
9          5   3080
10         5   1981
11         1   1679
12         2   2130
13         2    733
14         2   2742
15         4   2703
16         5    331
17         5   3863
18         1   3464
19         5   2759

In [ ]:
df["Total Price"] = (df["Price"] * df["Quantity"])

In [ ]:
df # profit , Sales Trackign , Business Growth

    Order_ID Product_Category  Price  Quantity  Customer_Rating  Total Price
0       1001            Books   1894         4              3.8         7576
1       1002      Electronics   2210         1              4.6         2210
2       1003         Clothing    897         2              4.2         1794
3       1004         Clothing   3890         1              2.8         3890
4       1005      Electronics   3529         3              3.6        10587
5       1006             Home   2228         2              4.7         4456
6       1007             Home    697         3              4.8         2091
7       1008             Home   2349         4              4.8         9396
8       1009             Home   3522         4              2.5        14088
9       1010             Home   3080         5              4.4        15400
10      1011             Home   1981         5              3.0         9905
11      1012      Electronics   1679         1              4.8         1679
12      1013             Home   2130         2              4.2         4260
13      1014             Home    733         2              2.9         1466
14      1015         Clothing   2742         2              2.6         5484
15      1016             Home   2703         4              5.0        10812
16      1017      Electronics    331         5              3.1         1655
17      1018      Electronics   3863         5              2.9        19315
18      1019      Electronics   3464         1              3.4         3464
19      1020         Clothing   2759         5              5.0        13795

In [ ]:
df["GST"] = df["Price"] * 0.18

In [ ]:
df

,Order_ID,Product_Category,Price,Quantity,Customer_Rating,Total Price,GST
0,1001,Books,1894,4,3.8,7576,340.92
1,1002,Electronics,2210,1,4.6,2210,397.80
2,1003,Clothing,897,2,4.2,1794,161.46
3,1004,Clothing,3890,1,2.8,3890,700.20
4,1005,Electronics,3529,3,3.6,10587,635.22
5,1006,Home,2228,2,4.7,4456,401.04
6,1007,Home,697,3,4.8,2091,125.46
7,1008,Home,2349,4,4.8,9396,422.82
8,1009,Home,3522,4,2.5,14088,633.96
9,1010,Home,3080,5,4.4,15400,554.40
10,1011,Home,1981,5,3.0,9905,356.58
11,1012,Electronics,1679,1,4.8,1679,302.22
12,1013,Home,2130,2,4.2,4260,383.40
13,1014,Home,733,2,2.9,1466,131.94
14,1015,Clothing,2742,2,2.6,5484,493.56
15,1016,Home,2703,4,5.0,10812,486.54
16,1017,Electronics,331,5,3.1,1655,59.58
17,1018,Electronics,3863,5,2.9,19315,695.34
18,1019,Electronics,3464,1,3.4,3464,623.52
19,1020,Clothing,2759,5,5.0,13795,496.62